# Generated by Django 2.2 on 2020-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
    ]
