# Generated by Django 2.2 on 2020-02-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='upploaded_by',
            new_name='uploaded_by',
        ),
    ]
